export const aboutParagraphs: string[] = [
  "När man vänder sig till mig för musik eller ljuddesign är det ofta för att man vill ha något annorlunda. Det generiska kan jag få till men det är framförallt musik som blandar, böjer och vrider på genrer som är min styrka.",
  "Mitt intresse för musik började tidigt, men länge valde jag bort musiken för akademiska studier. Efter att ha utbildat mig på universitetet och arbetat som journalist, blev jag under en intervju erbjuden att gå med i The Radio Dept., ett band jag beundrade. Jag började spela keyboards med dem, vilket ledde till skivsläpp, medverkan i storfilmer och internationella turnéer.",
  "År 2009 grundade jag duon Korallreven tillsammans med en vän, där vi gemensamt skrev och producerade all musik. Vi fick snabbt skivkontrakt i USA, vilket innebar intensiva år av musikskapande, inklusive låtskrivning för artister som Newkid, Lorentz och Jonathan Johansson.",
  "Sedan 2016 har jag fokuserat på att skapa musik och ljud för uppdrag åt bland andra Daniel Berlin Krog, Malmö Stadsteater och teaterkompaniet Bombina Bombast. Parallellt har jag undervisat vid högskolor i Malmö och Stockholm, drivit projekt med kulturförvaltningar och kulturinstitutioner samt analyserat och skrivit rapporter.",
  "Musikskapande är min största källa till glädje och inspiration, och det är när jag skapar musik som jag känner mig mest levande. Att bli kompositör innebar för mig en stor befrielse . Jag skriver musik för andra och slipper stå i rampljuset. Min musik är en del av något större – film, bild, eller meddelande – där den förstärker eller ger nya dimensioner. Jag älskar variationen: ena dagen dansmusik, nästa dag något för orkester, indie, ambient eller till och med mello. Musik är min passion i alla dess former.",
  "Jag är kompositör och ljuddesigner med fokus på skräddarsydd musik och ljudlandskap för film, teater och varumärken. Under åren har jag samarbetat med både välkända kulturinstitutioner och företag, främst i Sverige men även internationellt – bland annat med musik i reklam och film världen över.",
  "Tidigare var jag medlem i indiebanden The Radio Dept och Korallreven, där jag skrev låtar, producerade och turnerade. Jag har även skrivit för flera stora svenska popartister och en amerikansk världsstjärna, samt gjort egna konstprojekt och föreläst vid universitet.",
  "Sedan 2016 har jag främst arbetat med beställningsmusik och ljuddesign för exempelvis Daniel Berlin Krog, Malmö Stadsteater och teaterkompaniet Bombina Bombast. Parallellt har jag undervisat vid högskolor, drivit projekt tillsammans med kulturförvaltningar och skrivit analyser och rapporter.",
  "Att skapa musik är min största drivkraft och glädje. Jag trivs bäst bakom kulisserna där min musik får förstärka berättelser, bilder och upplevelser. Oavsett om det handlar om elektronisk dansmusik, cinematisk eller orkestrerad musik, indie, ambient eller något helt annat, så är variationen och utmaningen det som inspirerar mig mest."
];

export const getAboutExcerpt = (numberOfParagraphs: number = 1): string[] => {
  return aboutParagraphs.slice(0, numberOfParagraphs);
}; 
