backend:
  name: git-gateway
  branch: main
  local_backend: true # Enable local backend

# Media folders
media_folder: "public/media"
public_folder: "/media"

# Global site settings
site_url: "https://danieltjaeder.com"
display_url: "https://danieltjaeder.com"
logo_url: "/placeholder-logo.svg"

# Collections
collections:
  # Pages
  - name: "pages"
    label: "Pages"
    files:
      - file: "app/about/page.tsx"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Profile Image", name: "profileImage", widget: "image", required: false }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Contact Email", name: "contactEmail", widget: "string", required: false }
          - { label: "Social Links", name: "socialLinks", widget: "list", fields: [
              { label: "Platform", name: "platform", widget: "string" },
              { label: "URL", name: "url", widget: "string" }
            ]}

  # Compositions
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "SoundCloud URL", name: "soundcloud_url", widget: "string" }
      - { label: "Release Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  # Projects
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Project URL", name: "project_url", widget: "string", required: false }
      - { label: "Start Date", name: "start_date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Gallery", name: "gallery", widget: "list", fields: [
          { label: "Image", name: "image", widget: "image" },
          { label: "Caption", name: "caption", widget: "string", required: false }
        ]}
      - { label: "Technologies", name: "technologies", widget: "list" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  # Site Settings
  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/site.json"
        label: "Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Favicon", name: "favicon", widget: "image", required: false }
          - { label: "Meta Image", name: "metaImage", widget: "image", required: false }
          - { label: "Footer Text", name: "footerText", widget: "text", required: false }
          - { label: "Navigation", name: "navigation", widget: "list", fields: [
              { label: "Label", name: "label", widget: "string" },
              { label: "URL", name: "url", widget: "string" }
            ]} 
